openapi: 3.0.0
info:
  title: ' installation'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: Needs description.
paths:
  /installation:
    post:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
        - Avatar
        - Billing
        - Contract
        - Subscription
        - Bunqme
        - Fundraiser
        - Profile
        - Result
        - Tab
        - Response
        - Oauth
        - Client
        - Callback
        - Url
        - Card
        - Batch
        - Replace
        - Credit
        - Debit
        - Name
        - Certificate
        - Pinned
        - Challenge
        - Request
        - Company
        - Confirmation
        - Of
        - Funds
        - Chat
        - Conversation
        - Content
        - Export
        - Annual
        - Overview
        - Rib
        - Statement
        - Customer
        - Event
        - Credential
        - Password
        - Ip
        - Currency
        - Cloud
        - Beneficiary
        - Requirement
        - Payment
        - Quote
        - Conversion
        - Auto
        - Allocate
        - Definition
        - Device
        - Server
        - Draft
        - Csv
        - Pdf
        - Feature
        - Announcement
        - Generated
        - Cvc2
        - Ideal
        - Merchant
        - Insight
        - Preference
        - Date
        - Insights
        - Search
        - Installation
      summary: ''
      description: >-
        This is the only API call that does not require you to use the
        "X-Bunq-Client-Authentication" and "X-Bunq-Client-Signature" headers.
         You provide the server with the public part of the key pair that you are going to use to create the value of the signature header for all future API calls. The server creates an installation for you. Store the Installation Token and ServerPublicKey from the response. This token is used in the "X-Bunq-Client-Authentication" header for the creation of a DeviceServer and SessionServer.
    get:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
        - Avatar
        - Billing
        - Contract
        - Subscription
        - Bunqme
        - Fundraiser
        - Profile
        - Result
        - Tab
        - Response
        - Oauth
        - Client
        - Callback
        - Url
        - Card
        - Batch
        - Replace
        - Credit
        - Debit
        - Name
        - Certificate
        - Pinned
        - Challenge
        - Request
        - Company
        - Confirmation
        - Of
        - Funds
        - Chat
        - Conversation
        - Content
        - Export
        - Annual
        - Overview
        - Rib
        - Statement
        - Customer
        - Event
        - Credential
        - Password
        - Ip
        - Currency
        - Cloud
        - Beneficiary
        - Requirement
        - Payment
        - Quote
        - Conversion
        - Auto
        - Allocate
        - Definition
        - Device
        - Server
        - Draft
        - Csv
        - Pdf
        - Feature
        - Announcement
        - Generated
        - Cvc2
        - Ideal
        - Merchant
        - Insight
        - Preference
        - Date
        - Insights
        - Search
        - Installation
      summary: ''
      description: >-
        You must have an active session to make this call. This call returns the
        Id of the the Installation you are using in your session.
  /installation/{itemId}:
    get:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
        - Avatar
        - Billing
        - Contract
        - Subscription
        - Bunqme
        - Fundraiser
        - Profile
        - Result
        - Tab
        - Response
        - Oauth
        - Client
        - Callback
        - Url
        - Card
        - Batch
        - Replace
        - Credit
        - Debit
        - Name
        - Certificate
        - Pinned
        - Challenge
        - Request
        - Company
        - Confirmation
        - Of
        - Funds
        - Chat
        - Conversation
        - Content
        - Export
        - Annual
        - Overview
        - Rib
        - Statement
        - Customer
        - Event
        - Credential
        - Password
        - Ip
        - Currency
        - Cloud
        - Beneficiary
        - Requirement
        - Payment
        - Quote
        - Conversion
        - Auto
        - Allocate
        - Definition
        - Device
        - Server
        - Draft
        - Csv
        - Pdf
        - Feature
        - Announcement
        - Generated
        - Cvc2
        - Ideal
        - Merchant
        - Insight
        - Preference
        - Date
        - Insights
        - Search
        - Installation
      summary: ''
      description: >-
        You must have an active session to make this call. This call is used to
        check whether the Id you provide is the Id of your current installation
        or not.
  /installation/{installationID}/server-public-key:
    get:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
        - Avatar
        - Billing
        - Contract
        - Subscription
        - Bunqme
        - Fundraiser
        - Profile
        - Result
        - Tab
        - Response
        - Oauth
        - Client
        - Callback
        - Url
        - Card
        - Batch
        - Replace
        - Credit
        - Debit
        - Name
        - Certificate
        - Pinned
        - Challenge
        - Request
        - Company
        - Confirmation
        - Of
        - Funds
        - Chat
        - Conversation
        - Content
        - Export
        - Annual
        - Overview
        - Rib
        - Statement
        - Customer
        - Event
        - Credential
        - Password
        - Ip
        - Currency
        - Cloud
        - Beneficiary
        - Requirement
        - Payment
        - Quote
        - Conversion
        - Auto
        - Allocate
        - Definition
        - Device
        - Server
        - Draft
        - Csv
        - Pdf
        - Feature
        - Announcement
        - Generated
        - Cvc2
        - Ideal
        - Merchant
        - Insight
        - Preference
        - Date
        - Insights
        - Search
        - Installation
        - Instance
        - Invoice
        - Legal
        - Limit
        - Mastercard
        - Action
        - Bank
        - External
        - Savings
        - Joint
        - Adyen
        - Note
        - Switch
        - Service
        - Inquiry
        - Schedule
        - Sofort
        - Whitelist
        - Text
        - Notification
        - Filter
        - Email
        - Failure
        - Push
        - Provider
        - Issuer
        - Registry
        - Import
        - Splitwise
        - Settlement
        - Sandbox
        - Person
        - Error
        - Key
      summary: ''
      description: Show the ServerPublicKey for this Installation.
tags: []
components:
  schemas: {}
