openapi: 3.0.0
info:
  title: ' registry-import-splitwise-csv'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: Needs description.
paths:
  /registry-import-splitwise-csv:
    post:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
        - Avatar
        - Billing
        - Contract
        - Subscription
        - Bunqme
        - Fundraiser
        - Profile
        - Result
        - Tab
        - Response
        - Oauth
        - Client
        - Callback
        - Url
        - Card
        - Batch
        - Replace
        - Credit
        - Debit
        - Name
        - Certificate
        - Pinned
        - Challenge
        - Request
        - Company
        - Confirmation
        - Of
        - Funds
        - Chat
        - Conversation
        - Content
        - Export
        - Annual
        - Overview
        - Rib
        - Statement
        - Customer
        - Event
        - Credential
        - Password
        - Ip
        - Currency
        - Cloud
        - Beneficiary
        - Requirement
        - Payment
        - Quote
        - Conversion
        - Auto
        - Allocate
        - Definition
        - Device
        - Server
        - Draft
        - Csv
        - Pdf
        - Feature
        - Announcement
        - Generated
        - Cvc2
        - Ideal
        - Merchant
        - Insight
        - Preference
        - Date
        - Insights
        - Search
        - Installation
        - Instance
        - Invoice
        - Legal
        - Limit
        - Mastercard
        - Action
        - Bank
        - External
        - Savings
        - Joint
        - Adyen
        - Note
        - Switch
        - Service
        - Inquiry
        - Schedule
        - Sofort
        - Whitelist
        - Text
        - Notification
        - Filter
        - Email
        - Failure
        - Push
        - Provider
        - Issuer
        - Registry
        - Import
        - Splitwise
      summary: ''
      description: >-
        Used to upload a CSV export from Splitwise, and create a new Registry
        from it.
tags: []
components:
  schemas: {}
