openapi: 3.0.0
info:
  title: ' attachment-public'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: Needs description.
paths:
  /attachment-public:
    post:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
      summary: ''
      description: >-
        Create a new public attachment. Create a POST request with a payload
        that contains a binary representation of the file, without any JSON
        wrapping. Make sure you define the MIME type (i.e. image/jpeg, or
        image/png) in the Content-Type header. You are required to provide a
        description of the attachment using the X-Bunq-Attachment-Description
        header.
  /attachment-public/{itemId}:
    get:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
      summary: ''
      description: >-
        Get a specific attachment's metadata through its UUID. The Content-Type
        header of the response will describe the MIME type of the attachment
        file.
  /attachment-public/{attachment-publicUUID}/content:
    get:
      tags:
        - Id
        - Additional
        - Transaction
        - Information
        - Category
        - User
        - Defined
        - Monetary
        - Account
        - Attachment
        - Item
        - Public
        - Avatar
        - Billing
        - Contract
        - Subscription
        - Bunqme
        - Fundraiser
        - Profile
        - Result
        - Tab
        - Response
        - Oauth
        - Client
        - Callback
        - Url
        - Card
        - Batch
        - Replace
        - Credit
        - Debit
        - Name
        - Certificate
        - Pinned
        - Challenge
        - Request
        - Company
        - Confirmation
        - Of
        - Funds
        - Chat
        - Conversation
        - Content
      summary: ''
      description: Get the raw content of a specific attachment.
tags: []
components:
  schemas: {}
